### ISSUE TITLE
java.lang.Error: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by Macrophage001** [SlimeKnights/Mantle#50] opened 2016-03-17 19:16 UTC
I am getting an odd error with the latest version of mantle. The pastebin will tell you more but it seems to have something to do with your Flightpath class's post method.

Error:
http://pastebin.com/nbPFT7S0

Note: This is an error received on the 0.9.0 version of mantle, however I did receive the same error with the 0.9.1 version as well.

**Comment by bonii-xx** [comment] 2016-03-17 20:15
Do any of the other mods you have add molten gold?

**Comment by Protheus** [comment] 2016-03-17 21:49
getting the same error - here is my mod list (http://pastebin.com/e6VZsYQt)

java.lang.Error: java.lang.reflect.InvocationTargetException
	at slimeknights.mantle.pulsar.internal.BusExceptionHandler.handle(BusExceptionHandler.java:30)
	at slimeknights.mantle.pulsar.flightpath.Flightpath.post(Flightpath.java:92)
	at slimeknights.mantle.pulsar.control.PulseManager.propagateEvent(PulseManager.java:202)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:556)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at slimeknights.mantle.pulsar.flightpath.Flightpath.post(Flightpath.java:89)
	... 33 more
Caused by: java.lang.NullPointerException
	at net.minecraft.client.resources.model.ModelBakery.registerItemVariants(ModelBakery.java:759)
	at slimeknights.tconstruct.shared.FluidsClientProxy.registerFluidModels(FluidsClientProxy.java:45)
	at slimeknights.tconstruct.shared.FluidsClientProxy.registerModels(FluidsClientProxy.java:28)
	at slimeknights.tconstruct.common.CommonProxy.preInit(CommonProxy.java:27)
	at slimeknights.tconstruct.shared.TinkerFluids.preInit(TinkerFluids.java:236)
	... 38 more

**Comment by Macrophage001** [comment] 2016-03-17 23:10
I don't believe so. I'm having issues with some other mods right now too so I'll check asap.

**Comment by bonii-xx** [comment] 2016-03-18 09:22
https://github.com/SlimeKnights/TinkersConstruct/issues/1954

Gonna close this here, please post any information (aka which mod cause it to crash with tcon) in the tcon issue.

**Closed by bonii-xx** 2016-03-18 09:22 UTC

**Comment by rckymtnrfc** [comment] 2016-03-19 06:11
Posting this here too so Macrophage001 and Protheus see it.

------------------------

Check your TinkerModules.cfg in the config folder. Mine had an extra line in it that doesn't appear when I delete it and let it regenerate the file.

B:TinkerMaterials=true

With that removed, no more crash.

**Comment by Macrophage001** [comment] 2016-03-19 20:59
Mine still crashes with the same error unfortunately =/ I ran the mod by itself too and I still receive that same crash

**Comment by bonii-xx** [comment] 2016-03-19 21:48
Activate the smeltery or delete the TinkerModules.cfg
