### ISSUE TITLE
I'm not quite sure what is wrong.

### ISSUE THREAD

**Issue by Ae408-cmyk** [SlimeKnights/Mantle#171] opened 2021-12-24 16:45 UTC
[crash-2021-12-24_10.36.46-fml.txt](https://github.com/SlimeKnights/Mantle/files/7774852/crash-2021-12-24_10.36.46-fml.txt)

**Comment by Ae408-cmyk** [comment] 2021-12-24 16:47
The game doesn't crash, but it stops me at the error loading mods screen.

**Comment by KnightMiner** [comment] 2021-12-24 16:48
Duplicate of #168. Does no one read changelogs or take 5 seconds to check that the last 3 reported issues are the same as their issue?

**Closed as completed by KnightMiner** 2021-12-24 16:48 UTC
Labels: duplicate, 1.16
