### ISSUE TITLE
java.lang.IllegalAccessError

### ISSUE THREAD

**Issue by zhourui123** [SlimeKnights/Mantle#125] opened 2019-07-23 00:44 UTC
The versions and modules are the same, but some players crash, this is very strange
```
java.lang.IllegalAccessError: tried to access field net.minecraft.block.Block.field_149772_a from class slimeknights.mantle.block.BlockStairsBase
	at slimeknights.mantle.block.BlockStairsBase.<init>(BlockStairsBase.java:12)
	at slimeknights.tconstruct.common.TinkerPulse.registerBlockStairsFrom(TinkerPulse.java:72)

```

https://gist.github.com/zhourui123/8f481263c7d5e7a73245b7dae1ff22e5

**Comment by KnightMiner** [comment] 2019-07-23 02:32
Can you reproduce this with fewer mods? This crash is caused by some core mod breaking access transformers, I have seen it before but never know the real cause.

**Comment by zhourui123** [comment] 2019-07-23 02:48
Sorry it's not easy to reproduce, Since this happens only on players' computers and by accident, mod is not easy to change since it is downloaded and md5 checked by Chinese MC Official Netease.

**Comment by zhourui123** [comment] 2019-07-23 09:06
I looked carefully, not sure if 'FileNotFoundException' caused the _at file was not added correctly.
Can you take a look at it for me?
thank you !
https://gist.github.com/zhourui123/1f4ac091ae2fda02d0c70103d55b8614
Although this log is CTM's, I believe it is the same problem

**Comment by bonii-xx** [comment] 2019-08-20 17:32
Those issues usually come from mods breaking things inside Minecraft, which then impact other mods. What KnightMiner is referring to by core mods. This can only be found by reproducing the crash and removing (core)mods until it works.

The _at file you're mentioning takes care of the access which causes the error. So if it's not applied, an error like this will occur.

**Comment by ppoozl** [comment] 2020-01-26 10:24
Netease's Minecraft Forge may be modified. And maybe the mod itself is modified too.

**Comment by KnightMiner** [comment] 2020-08-05 18:03
Closing for lack of information. The fact that just one user out of the thousands that use Mantle has this problem means its certainly a core mod breaking stuff, and 1.15 no longer has this problem at all (that class is deleted)

**Closed by KnightMiner** 2020-08-05 18:03 UTC
